version: '3'

services:
  backend:
    build: ./ddos_backend
    ports:
      - "5000:5000"
    volumes:
      - ./ddos_backend:/app
    environment:
      - FLASK_ENV=development
    command: python3 app.py

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev -- --host

networks:
  sage-shield-network:
    driver: bridge
